package Vistas;

/**
 * @author Grupo 15 Luis Ezequiel Sosa Lucas Saidman Luca Rodrigaño Ignacio
 * Rodriguez
 *
 */
public class App extends javax.swing.JFrame {
    
    private VistaEntradas vistaEntradas;
    private VistaFunciones vistaFunciones;
    private VistaPelicula vistaPelicula;
    private VistaSalas vistaSalas;
    private VistaTicketsVentas vistaTicketsVentas;
    private VistaVentaOnline vistaVentaOnline;
    private VistaVentaPresencial vistaVentaPresencial;

    /**
     * Creates new form App
     */
    public App() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jm_gestion = new javax.swing.JMenu();
        jmi_gestion_peliculas = new javax.swing.JMenuItem();
        jmi_gestion_funciones = new javax.swing.JMenuItem();
        jmi_gestion_salas = new javax.swing.JMenuItem();
        jm_ventas = new javax.swing.JMenu();
        jmi_venta_presencial = new javax.swing.JMenuItem();
        jmi_venta_online = new javax.swing.JMenuItem();
        jm_ticket = new javax.swing.JMenu();
        jmi_tickets_ventas = new javax.swing.JMenuItem();
        jmi_tickets_entradas = new javax.swing.JMenuItem();
        jm_salir = new javax.swing.JMenu();
        jmi_salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 677, Short.MAX_VALUE)
        );

        jm_gestion.setText("Gestion");

        jmi_gestion_peliculas.setText("Peliculas");
        jmi_gestion_peliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_gestion_peliculasActionPerformed(evt);
            }
        });
        jm_gestion.add(jmi_gestion_peliculas);

        jmi_gestion_funciones.setText("Funciones");
        jmi_gestion_funciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_gestion_funcionesActionPerformed(evt);
            }
        });
        jm_gestion.add(jmi_gestion_funciones);

        jmi_gestion_salas.setText("Salas");
        jmi_gestion_salas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_gestion_salasActionPerformed(evt);
            }
        });
        jm_gestion.add(jmi_gestion_salas);

        jMenuBar1.add(jm_gestion);

        jm_ventas.setText("Ventas");

        jmi_venta_presencial.setText("Presencial");
        jmi_venta_presencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_venta_presencialActionPerformed(evt);
            }
        });
        jm_ventas.add(jmi_venta_presencial);

        jmi_venta_online.setText("Online");
        jmi_venta_online.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_venta_onlineActionPerformed(evt);
            }
        });
        jm_ventas.add(jmi_venta_online);

        jMenuBar1.add(jm_ventas);

        jm_ticket.setText("Ticket");

        jmi_tickets_ventas.setText("Tickets de Ventas");
        jmi_tickets_ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_tickets_ventasActionPerformed(evt);
            }
        });
        jm_ticket.add(jmi_tickets_ventas);

        jmi_tickets_entradas.setText("Entradas");
        jmi_tickets_entradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_tickets_entradasActionPerformed(evt);
            }
        });
        jm_ticket.add(jmi_tickets_entradas);

        jMenuBar1.add(jm_ticket);

        jm_salir.setText("Salir");

        jmi_salir.setText("Salir");
        jmi_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_salirActionPerformed(evt);
            }
        });
        jm_salir.add(jmi_salir);

        jMenuBar1.add(jm_salir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_salirActionPerformed
        dispose();
    }//GEN-LAST:event_jmi_salirActionPerformed

    private void jmi_tickets_ventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_tickets_ventasActionPerformed
        if(vistaTicketsVentas == null || vistaTicketsVentas.isClosed()){
            vistaTicketsVentas = new Vistas.VistaTicketsVentas();
            Escritorio.add(vistaTicketsVentas);
            vistaTicketsVentas.setVisible(true);
        }; 
    }//GEN-LAST:event_jmi_tickets_ventasActionPerformed

    private void jmi_gestion_peliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_gestion_peliculasActionPerformed
        if(vistaPelicula == null || vistaPelicula.isClosed()){
            vistaPelicula = new Vistas.VistaPelicula();
            Escritorio.add(vistaPelicula);
            vistaPelicula.setVisible(true);
        }; 
    }//GEN-LAST:event_jmi_gestion_peliculasActionPerformed

    private void jmi_gestion_funcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_gestion_funcionesActionPerformed
        if(vistaFunciones == null || vistaFunciones.isClosed()){
            vistaFunciones = new Vistas.VistaFunciones();
            Escritorio.add(vistaFunciones);
            vistaFunciones.setVisible(true);
        }; 
    }//GEN-LAST:event_jmi_gestion_funcionesActionPerformed

    private void jmi_gestion_salasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_gestion_salasActionPerformed
        if(vistaSalas == null || vistaSalas.isClosed()){
            vistaSalas = new Vistas.VistaSalas();
            Escritorio.add(vistaSalas);
            vistaSalas.setVisible(true);
        };
    }//GEN-LAST:event_jmi_gestion_salasActionPerformed

    private void jmi_venta_presencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_venta_presencialActionPerformed
        if(vistaVentaPresencial == null || vistaVentaPresencial.isClosed()){
            vistaVentaPresencial = new Vistas.VistaVentaPresencial();
            Escritorio.add(vistaVentaPresencial);
            vistaVentaPresencial.setVisible(true);
        };
    }//GEN-LAST:event_jmi_venta_presencialActionPerformed

    private void jmi_venta_onlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_venta_onlineActionPerformed
        if(vistaVentaOnline == null || vistaVentaOnline.isClosed()){
            vistaVentaOnline = new Vistas.VistaVentaOnline();
            Escritorio.add(vistaVentaOnline);
            vistaVentaOnline.setVisible(true);
        };
    }//GEN-LAST:event_jmi_venta_onlineActionPerformed

    private void jmi_tickets_entradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_tickets_entradasActionPerformed
        if(vistaEntradas == null || vistaEntradas.isClosed()){
            vistaEntradas = new Vistas.VistaEntradas();
            Escritorio.add(vistaEntradas);
            vistaEntradas.setVisible(true);
        };
    }//GEN-LAST:event_jmi_tickets_entradasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jm_gestion;
    private javax.swing.JMenu jm_salir;
    private javax.swing.JMenu jm_ticket;
    private javax.swing.JMenu jm_ventas;
    private javax.swing.JMenuItem jmi_gestion_funciones;
    private javax.swing.JMenuItem jmi_gestion_peliculas;
    private javax.swing.JMenuItem jmi_gestion_salas;
    private javax.swing.JMenuItem jmi_salir;
    private javax.swing.JMenuItem jmi_tickets_entradas;
    private javax.swing.JMenuItem jmi_tickets_ventas;
    private javax.swing.JMenuItem jmi_venta_online;
    private javax.swing.JMenuItem jmi_venta_presencial;
    // End of variables declaration//GEN-END:variables
}
