package Vistas;

/** 
    @author Grupo 15
    Luis Ezequiel Sosa
    Lucas Saidman
    Luca Rodrigaño
    Ignacio Rodriguez
**/

public class App extends javax.swing.JFrame {

    /**
     * Creates new form App
     */
    public App() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jm_gestion = new javax.swing.JMenu();
        jmi_gestion_asientos = new javax.swing.JMenuItem();
        jm_venta = new javax.swing.JMenu();
        jmi_venta_presencial = new javax.swing.JMenuItem();
        jmi_venta_online = new javax.swing.JMenuItem();
        jm_ticket = new javax.swing.JMenu();
        jmi_tickets_ventas = new javax.swing.JMenuItem();
        jmi_tickets_entradas = new javax.swing.JMenuItem();
        jm_salir = new javax.swing.JMenu();
        jmi_salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 677, Short.MAX_VALUE)
        );

        jm_gestion.setText("Compradores");

        jmi_gestion_asientos.setText("Compradores");
        jm_gestion.add(jmi_gestion_asientos);

        jMenuBar1.add(jm_gestion);

        jm_venta.setText("Venta");

        jmi_venta_presencial.setText("Venta Presencial");
        jm_venta.add(jmi_venta_presencial);

        jmi_venta_online.setText("Venta Online");
        jm_venta.add(jmi_venta_online);

        jMenuBar1.add(jm_venta);

        jm_ticket.setText("Ticket");

        jmi_tickets_ventas.setText("Tickets de Ventas");
        jm_ticket.add(jmi_tickets_ventas);

        jmi_tickets_entradas.setText("Entradas");
        jm_ticket.add(jmi_tickets_entradas);

        jMenuBar1.add(jm_ticket);

        jm_salir.setText("Salir");

        jmi_salir.setText("Salir");
        jmi_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_salirActionPerformed(evt);
            }
        });
        jm_salir.add(jmi_salir);

        jMenuBar1.add(jm_salir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_salirActionPerformed
        dispose();
    }//GEN-LAST:event_jmi_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jm_gestion;
    private javax.swing.JMenu jm_salir;
    private javax.swing.JMenu jm_ticket;
    private javax.swing.JMenu jm_venta;
    private javax.swing.JMenuItem jmi_gestion_asientos;
    private javax.swing.JMenuItem jmi_salir;
    private javax.swing.JMenuItem jmi_tickets_entradas;
    private javax.swing.JMenuItem jmi_tickets_ventas;
    private javax.swing.JMenuItem jmi_venta_online;
    private javax.swing.JMenuItem jmi_venta_presencial;
    // End of variables declaration//GEN-END:variables
}
