package Vistas;

import Modelo.Asiento;
import Modelo.Comprador;
import Modelo.DetalleTicket;
import Modelo.Funcion;
import Modelo.Pelicula;
import Modelo.Sala;
import Modelo.TicketCompra;

import Persistencia.AsientoData;
import Persistencia.CompradorData;
import Persistencia.DetalleTicketData;
import Persistencia.FuncionData;
import Persistencia.PeliculaData;
import Persistencia.SalaData;
import Persistencia.TicketCompraData;

import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class VistaVentaPresencial extends javax.swing.JInternalFrame {

    private final CompradorData compradorDao = new CompradorData();
    private Comprador compradorActual = null;
    private final PeliculaData peliculaDao = new PeliculaData();
    private List<Pelicula> listaPeliculas = new ArrayList<>();
    private final FuncionData funcionDao = new FuncionData();
    private List<Funcion> listaFunciones = new ArrayList<>();

    public VistaVentaPresencial() {
        initComponents();
        cargarPeliculas();
        txtNombreComprador.setEnabled(false);
        jDateComprador.setEnabled(false);
        btnAgregarComprador.setEnabled(false);
        cbPeliculas.addActionListener(e -> cargarFormatosPorPelicula());

    }

    //Cliente
    private Integer parseEntero(String s) {
        try {
            return Integer.parseInt(s.trim());
        } catch (Exception e) {
            return null;
        }
    }

    private boolean esSoloTexto(String texto) {
        if (texto == null || texto.trim().isEmpty()) {
            return false;
        }
        for (char c : texto.toCharArray()) {
            if (!Character.isLetter(c) && !Character.isSpaceChar(c)) {
                return false;
            }
        }
        return true;
    }

    //Peliculas
    private void cargarPeliculas() {
        try {
            listaPeliculas = peliculaDao.listarPeliculas();
            cbPeliculas.removeAllItems();

            boolean hayPeliculas = false;
            for (Pelicula p : listaPeliculas) {
                if (p.isEnCartelera()) {
                    cbPeliculas.addItem(p.getTitulo());
                    hayPeliculas = true;
                }
            }

            if (!hayPeliculas) {
                cbPeliculas.addItem("No hay peliculas en cartelera");
                cbPeliculas.setEnabled(false);
            } else {
                cbPeliculas.setEnabled(true);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al cargar las peliculas: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void cargarFormatosPorPelicula() {
    cbFormatoIdioma.removeAllItems();
    listaFunciones.clear();

    String tituloSeleccionado = (String) cbPeliculas.getSelectedItem();
    if (tituloSeleccionado == null || tituloSeleccionado.equals("No hay peliculas en cartelera")) {
        return;
    }

    Pelicula peliculaSeleccionada = null;
    for (Pelicula p : listaPeliculas) {
        if (p.getTitulo().equalsIgnoreCase(tituloSeleccionado)) {
            peliculaSeleccionada = p;
            break;
        }
    }

    if (peliculaSeleccionada == null) return;

    try {
        listaFunciones = funcionDao.listarPorPelicula(peliculaSeleccionada.getIdPelicula());

        java.util.Set<String> formatosUnicos = new java.util.HashSet<>();

        for (Funcion f : listaFunciones) {
            String formato = (f.isEs3d() ? "3D" : "2D");
            String idioma = f.getIdioma();
            String combinado = formato + " - " + idioma;

            formatosUnicos.add(combinado);
        }

        if (formatosUnicos.isEmpty()) {
            cbFormatoIdioma.addItem("Sin funciones disponibles");
            cbFormatoIdioma.setEnabled(false);
        } else {
            for (String f : formatosUnicos) {
                cbFormatoIdioma.addItem(f);
            }
            cbFormatoIdioma.setEnabled(true);
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al cargar los formatos: " + e.getMessage());
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_vta_presencial = new javax.swing.JPanel();
        lblTituloCliente = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        lblDNI = new javax.swing.JLabel();
        txtFieldDNI = new javax.swing.JTextField();
        lblFecha = new javax.swing.JLabel();
        lblNombreComprador = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        txtNombreComprador = new javax.swing.JTextField();
        jDateComprador = new com.toedter.calendar.JDateChooser();
        cbFechasDisponibles = new javax.swing.JComboBox<>();
        cbHoras = new javax.swing.JComboBox<>();
        lblPeliculaTitulo = new javax.swing.JLabel();
        lblSelectAsiento = new javax.swing.JLabel();
        btnBuscarComprador = new javax.swing.JButton();
        lblFechaNac = new javax.swing.JLabel();
        btnAgregarComprador = new javax.swing.JButton();
        lblFormato = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblPago = new javax.swing.JLabel();
        lblPelicula = new javax.swing.JLabel();
        lblMetodoPago = new javax.swing.JLabel();
        cbMedioPago = new javax.swing.JComboBox<>();
        lblPrecio = new javax.swing.JLabel();
        cbPeliculas = new javax.swing.JComboBox<>();
        lblCantidad = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        txtFieldPrecioUnit = new javax.swing.JTextField();
        txtFieldCantidad = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        btnCompra = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cbFormatoIdioma = new javax.swing.JComboBox<>();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jToggleButton10 = new javax.swing.JToggleButton();
        jToggleButton11 = new javax.swing.JToggleButton();
        jToggleButton12 = new javax.swing.JToggleButton();
        jToggleButton13 = new javax.swing.JToggleButton();
        jToggleButton14 = new javax.swing.JToggleButton();
        jToggleButton15 = new javax.swing.JToggleButton();
        jToggleButton16 = new javax.swing.JToggleButton();
        jToggleButton17 = new javax.swing.JToggleButton();
        jToggleButton18 = new javax.swing.JToggleButton();
        jToggleButton19 = new javax.swing.JToggleButton();
        jToggleButton20 = new javax.swing.JToggleButton();
        jToggleButton21 = new javax.swing.JToggleButton();
        jToggleButton22 = new javax.swing.JToggleButton();
        jToggleButton23 = new javax.swing.JToggleButton();
        jToggleButton24 = new javax.swing.JToggleButton();
        jToggleButton25 = new javax.swing.JToggleButton();
        jToggleButton26 = new javax.swing.JToggleButton();
        jToggleButton27 = new javax.swing.JToggleButton();
        jToggleButton28 = new javax.swing.JToggleButton();
        jToggleButton29 = new javax.swing.JToggleButton();
        jToggleButton30 = new javax.swing.JToggleButton();
        jToggleButton31 = new javax.swing.JToggleButton();
        jToggleButton32 = new javax.swing.JToggleButton();
        jToggleButton33 = new javax.swing.JToggleButton();
        jToggleButton34 = new javax.swing.JToggleButton();
        jToggleButton35 = new javax.swing.JToggleButton();
        jToggleButton36 = new javax.swing.JToggleButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(1000, 700));

        pnl_vta_presencial.setPreferredSize(new java.awt.Dimension(1000, 699));

        lblTituloCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTituloCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloCliente.setText("Cliente");

        btnSalir.setText("Salir");

        lblDNI.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDNI.setText("DNI:");

        txtFieldDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldDNIActionPerformed(evt);
            }
        });

        lblFecha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFecha.setText("Funciones Disponibles");

        lblNombreComprador.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNombreComprador.setText("Nombre y Apellido:");

        btnCancelar.setText("Cancelar y Limpiar");

        txtNombreComprador.setText("Nombre y Apellido Cliente");

        jDateComprador.setMinSelectableDate(new java.util.Date(-62135755096000L));

        lblPeliculaTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPeliculaTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPeliculaTitulo.setText("Pelicula");

        lblSelectAsiento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSelectAsiento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSelectAsiento.setText("Seleccionar Asientos");

        btnBuscarComprador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-magnifying-glass-tilted-right-48.png"))); // NOI18N
        btnBuscarComprador.setText("Buscar");
        btnBuscarComprador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCompradorActionPerformed(evt);
            }
        });

        lblFechaNac.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFechaNac.setText("Fecha de Nacimiento");

        btnAgregarComprador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/guardar.png"))); // NOI18N
        btnAgregarComprador.setText("Guardar");
        btnAgregarComprador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCompradorActionPerformed(evt);
            }
        });

        lblFormato.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFormato.setText("Formato e Idioma: ");

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Venta de Entradas Mostrador");

        lblPago.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPago.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPago.setText("Pago y Confirmacion");

        lblPelicula.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPelicula.setText("Cartelera");

        lblMetodoPago.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMetodoPago.setText("Metodo de Pago");

        lblPrecio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPrecio.setText("Precio Unitario: ");

        lblCantidad.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblCantidad.setText("Cantidad: ");

        lblTotal.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblTotal.setText("Total:");

        btnCompra.setText("Confirmar Compra");

        jLabel3.setBackground(new java.awt.Color(0, 0, 51));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Pantalla");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 204)));

        jToggleButton7.setText("|A1|");

        jToggleButton8.setText("|A2|");

        jToggleButton9.setText("|A2|");

        jToggleButton10.setText("|A2|");

        jToggleButton11.setText("|A2|");

        jToggleButton12.setText("|A2|");

        jToggleButton13.setText("|A1|");

        jToggleButton14.setText("|A2|");

        jToggleButton15.setText("|A2|");

        jToggleButton16.setText("|A2|");

        jToggleButton17.setText("|A2|");

        jToggleButton18.setText("|A2|");

        jToggleButton19.setText("|A1|");

        jToggleButton20.setText("|A2|");

        jToggleButton21.setText("|A2|");

        jToggleButton22.setText("|A2|");

        jToggleButton23.setText("|A2|");

        jToggleButton24.setText("|A2|");

        jToggleButton25.setText("|A1|");

        jToggleButton26.setText("|A2|");

        jToggleButton27.setText("|A2|");

        jToggleButton28.setText("|A2|");

        jToggleButton29.setText("|A2|");

        jToggleButton30.setText("|A2|");

        jToggleButton31.setText("|A1|");

        jToggleButton32.setText("|A2|");

        jToggleButton33.setText("|A2|");

        jToggleButton34.setText("|A2|");

        jToggleButton35.setText("|A2|");

        jToggleButton36.setText("|A2|");

        javax.swing.GroupLayout pnl_vta_presencialLayout = new javax.swing.GroupLayout(pnl_vta_presencial);
        pnl_vta_presencial.setLayout(pnl_vta_presencialLayout);
        pnl_vta_presencialLayout.setHorizontalGroup(
            pnl_vta_presencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_vta_presencialLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(pnl_vta_presencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_vta_presencialLayout.createSequentialGroup()
                        .addGroup(pnl_vta_presencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnl_vta_presencialLayout.createSequentialGroup()
                                .addComponent(btnCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_vta_presencialLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(lblTituloCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_vta_presencialLayout.createSequentialGroup()
                                .addComponent(lblPrecio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFieldPrecioUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblCantidad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_vta_presencialLayout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(lblPago, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnl_vta_presencialLayout.createSequentialGroup()
                        .addGroup(pnl_vta_presencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnl_vta_presencialLayout.createSequentialGroup()
                                .addGroup(pnl_vta_presencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombreComprador)
                                    .addComponent(lblFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1)
                                .addGroup(pnl_vta_presencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnl_vta_presencialLayout.createSequentialGroup()
                                        .addComponent(jDateComprador, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnAgregarComprador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(txtNombreComprador, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnl_vta_presencialLayout.createSequentialGroup()
                                .addComponent(lblDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(txtFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(btnBuscarComprador, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(150, 150, 150)
                        .addGroup(pnl_vta_presencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnl_vta_presencialLayout.createSequentialGroup()
                                .addComponent(jToggleButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton24))
                            .addGroup(pnl_vta_presencialLayout.createSequentialGroup()
                                .addComponent(jToggleButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton30))
                            .addComponent(lblSelectAsiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 37, Short.MAX_VALUE))
                    .addGroup(pnl_vta_presencialLayout.createSequentialGroup()
                        .addGroup(pnl_vta_presencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFormato, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnl_vta_presencialLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(lblPeliculaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_vta_presencialLayout.createSequentialGroup()
                                .addComponent(lblMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbMedioPago, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_vta_presencialLayout.createSequentialGroup()
                                .addGroup(pnl_vta_presencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFecha, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(pnl_vta_presencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbFormatoIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnl_vta_presencialLayout.createSequentialGroup()
                                        .addComponent(cbFechasDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnl_vta_presencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnl_vta_presencialLayout.createSequentialGroup()
                                .addComponent(jToggleButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton12))
                            .addGroup(pnl_vta_presencialLayout.createSequentialGroup()
                                .addComponent(jToggleButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton18))
                            .addGroup(pnl_vta_presencialLayout.createSequentialGroup()
                                .addComponent(jToggleButton31, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton35)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton36)))
                        .addGap(37, 37, 37))))
        );
        pnl_vta_presencialLayout.setVerticalGroup(
            pnl_vta_presencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_vta_presencialLayout.createSequentialGroup()
                .addGroup(pnl_vta_presencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_vta_presencialLayout.createSequentialGroup()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(lblTituloCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnl_vta_presencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarComprador, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(pnl_vta_presencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombreComprador, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreComprador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_vta_presencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnl_vta_presencialLayout.createSequentialGroup()
                                .addGroup(pnl_vta_presencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFechaNac)
                                    .addComponent(jDateComprador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                .addComponent(lblPeliculaTitulo)
                                .addGap(26, 26, 26))
                            .addGroup(pnl_vta_presencialLayout.createSequentialGroup()
                                .addComponent(btnAgregarComprador, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(pnl_vta_presencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_vta_presencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbFormatoIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFormato, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_vta_presencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbFechasDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(lblPago, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_vta_presencialLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(lblSelectAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnl_vta_presencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jToggleButton25)
                            .addComponent(jToggleButton26)
                            .addComponent(jToggleButton27)
                            .addComponent(jToggleButton28)
                            .addComponent(jToggleButton29)
                            .addComponent(jToggleButton30))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_vta_presencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jToggleButton19)
                            .addComponent(jToggleButton20)
                            .addComponent(jToggleButton21)
                            .addComponent(jToggleButton22)
                            .addComponent(jToggleButton23)
                            .addComponent(jToggleButton24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_vta_presencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jToggleButton13)
                            .addComponent(jToggleButton14)
                            .addComponent(jToggleButton15)
                            .addComponent(jToggleButton16)
                            .addComponent(jToggleButton17)
                            .addComponent(jToggleButton18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_vta_presencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jToggleButton7)
                            .addComponent(jToggleButton8)
                            .addComponent(jToggleButton9)
                            .addComponent(jToggleButton10)
                            .addComponent(jToggleButton11)
                            .addComponent(jToggleButton12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_vta_presencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jToggleButton31)
                            .addComponent(jToggleButton32)
                            .addComponent(jToggleButton33)
                            .addComponent(jToggleButton34)
                            .addComponent(jToggleButton35)
                            .addComponent(jToggleButton36))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(pnl_vta_presencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMedioPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_vta_presencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldPrecioUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(pnl_vta_presencialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCompra)
                    .addComponent(btnCancelar)
                    .addComponent(btnSalir))
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_vta_presencial, javax.swing.GroupLayout.PREFERRED_SIZE, 994, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_vta_presencial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFieldDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldDNIActionPerformed

    private void btnBuscarCompradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCompradorActionPerformed
        String dniTexto = txtFieldDNI.getText().trim();
        if (dniTexto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un DNI");
            txtFieldDNI.requestFocus();
            return;
        }

        if (dniTexto.length() != 8) {
            JOptionPane.showMessageDialog(this, "El DNI debe tener 8 digitos");
            txtFieldDNI.requestFocus();
            return;
        }

        Integer dni = null;
        try {
            dni = Integer.parseInt(dniTexto);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El DNI solo debe contener numeros");
            txtFieldDNI.requestFocus();
            return;
        }

        try {
            Comprador c = compradorDao.buscarPorDni(dni);
            if (c == null) {
                JOptionPane.showMessageDialog(this,
                        "No existe un cliente con ese DNI.\nComplete los datos para registrarlo.");

                compradorActual = null;
                txtNombreComprador.setText("");
                jDateComprador.setDate(null);

                txtNombreComprador.setEnabled(true);
                jDateComprador.setEnabled(true);
                btnAgregarComprador.setEnabled(true);
                return;
            }

            compradorActual = c;
            txtNombreComprador.setText(c.getNombre());
            if (c.getFecha_nac() != null) {
                jDateComprador.setDate(c.getFecha_nac());
            } else {
                jDateComprador.setDate(null);
            }

            txtNombreComprador.setEnabled(false);
            jDateComprador.setEnabled(false);
            btnAgregarComprador.setEnabled(false);

            JOptionPane.showMessageDialog(this, "Cliente encontrado: " + c.getNombre());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al buscar Cliente: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnBuscarCompradorActionPerformed

    private void btnAgregarCompradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCompradorActionPerformed
        if (compradorActual != null) {
            JOptionPane.showMessageDialog(this, "El cliente ya existe en la base de datos");
            return;
        }

        String nombre = txtNombreComprador.getText().trim();
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el nombre y apellido del Cliente");
            txtNombreComprador.requestFocus();
            return;
        }

        if (!esSoloTexto(nombre)) {
            JOptionPane.showMessageDialog(this, "El nombre solo puede contener letras y espacios");
            txtNombreComprador.requestFocus();
            txtNombreComprador.selectAll();
            return;
        }

        java.util.Date fechaNac = jDateComprador.getDate();
        if (fechaNac == null) {
            JOptionPane.showMessageDialog(this, "Seleccione la fecha de nacimiento");
            jDateComprador.requestFocus();
            return;
        }

        if (fechaNac.after(new java.util.Date())) {
            JOptionPane.showMessageDialog(this, "La fecha de nacimiento no puede ser mayor a la actual");
            jDateComprador.requestFocus();
            return;
        }

        try {
            Integer dni = Integer.parseInt(txtFieldDNI.getText().trim());
            Comprador nuevo = new Comprador();
            nuevo.setDni(dni);
            nuevo.setNombre(nombre);
            nuevo.setFecha_nac(fechaNac);

            compradorDao.crear(nuevo);

            JOptionPane.showMessageDialog(this, "Cliente agregado correctamente");

            txtNombreComprador.setEnabled(false);
            jDateComprador.setEnabled(false);
            btnAgregarComprador.setEnabled(false);

            compradorActual = nuevo;

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al guardar el cliente: " + e.getMessage());
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnAgregarCompradorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarComprador;
    private javax.swing.JButton btnBuscarComprador;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCompra;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbFechasDisponibles;
    private javax.swing.JComboBox<String> cbFormatoIdioma;
    private javax.swing.JComboBox<String> cbHoras;
    private javax.swing.JComboBox<String> cbMedioPago;
    private javax.swing.JComboBox<String> cbPeliculas;
    private com.toedter.calendar.JDateChooser jDateComprador;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton12;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton14;
    private javax.swing.JToggleButton jToggleButton15;
    private javax.swing.JToggleButton jToggleButton16;
    private javax.swing.JToggleButton jToggleButton17;
    private javax.swing.JToggleButton jToggleButton18;
    private javax.swing.JToggleButton jToggleButton19;
    private javax.swing.JToggleButton jToggleButton20;
    private javax.swing.JToggleButton jToggleButton21;
    private javax.swing.JToggleButton jToggleButton22;
    private javax.swing.JToggleButton jToggleButton23;
    private javax.swing.JToggleButton jToggleButton24;
    private javax.swing.JToggleButton jToggleButton25;
    private javax.swing.JToggleButton jToggleButton26;
    private javax.swing.JToggleButton jToggleButton27;
    private javax.swing.JToggleButton jToggleButton28;
    private javax.swing.JToggleButton jToggleButton29;
    private javax.swing.JToggleButton jToggleButton30;
    private javax.swing.JToggleButton jToggleButton31;
    private javax.swing.JToggleButton jToggleButton32;
    private javax.swing.JToggleButton jToggleButton33;
    private javax.swing.JToggleButton jToggleButton34;
    private javax.swing.JToggleButton jToggleButton35;
    private javax.swing.JToggleButton jToggleButton36;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblDNI;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFechaNac;
    private javax.swing.JLabel lblFormato;
    private javax.swing.JLabel lblMetodoPago;
    private javax.swing.JLabel lblNombreComprador;
    private javax.swing.JLabel lblPago;
    private javax.swing.JLabel lblPelicula;
    private javax.swing.JLabel lblPeliculaTitulo;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblSelectAsiento;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloCliente;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel pnl_vta_presencial;
    private javax.swing.JTextField txtFieldCantidad;
    private javax.swing.JTextField txtFieldDNI;
    private javax.swing.JTextField txtFieldPrecioUnit;
    private javax.swing.JTextField txtNombreComprador;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
