/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Modelo.Pelicula;
import javax.swing.JOptionPane;
import Persistencia.PeliculaData;
import com.toedter.calendar.JDateChooser;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JComboBox;

/**
 *
 * @author Usuario
 */
public class VistaPelicula extends javax.swing.JInternalFrame {

    private PeliculaData peliculaData;

    /**
     * Creates new form VistaPelicula
     */
    public VistaPelicula() {
        initComponents();
        peliculaData = new PeliculaData();

        txtID.setEditable(true);

        javax.swing.event.DocumentListener listenerTexto = new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                reglasHabilitacion();
            }

            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                reglasHabilitacion();
            }

            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                reglasHabilitacion();
            }
        };

        txtTitulo.getDocument().addDocumentListener(listenerTexto);
        txtDirector.getDocument().addDocumentListener(listenerTexto);
        txtActores.getDocument().addDocumentListener(listenerTexto);
        txtorigen.getDocument().addDocumentListener(listenerTexto);

        cbGenero.addActionListener(e -> reglasHabilitacion());
        fechaSeleccionada.getDateEditor().addPropertyChangeListener(evt -> {
            if ("date".equals(evt.getPropertyName())) {
                reglasHabilitacion();
            }
        });
        rbDisponible.addActionListener(e -> reglasHabilitacion());
        rbNodisponible.addActionListener(e -> reglasHabilitacion());

        txtID.setText("");

        txtID.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                reglasHabilitacion();
            }

            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                reglasHabilitacion();
            }

            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                reglasHabilitacion();
            }
        });

        fechaSeleccionada.setMinSelectableDate(new java.util.GregorianCalendar(2000, Calendar.JANUARY, 1).getTime());
        fechaSeleccionada.setMaxSelectableDate(new java.util.Date());

        cbGenero.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[]{"Accion", "Comedia", "Drama", "Ciencia Ficcion", "Terror", "Romance", "Animacion"}
        ));

        configurarTabla();

        jtPeliculas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int fila = jtPeliculas.getSelectedRow();
                if (fila >= 0) {
                    cargarDatosDesdeTabla(fila);
                }
            }
        });

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Control de Peliculas");

        actualizarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDirector = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtActores = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtorigen = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbGenero = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        fechaSeleccionada = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        rbDisponible = new javax.swing.JRadioButton();
        rbNodisponible = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtPeliculas = new javax.swing.JTable();
        bttAgg = new javax.swing.JButton();
        bttBuscar = new javax.swing.JButton();
        bttUpdate = new javax.swing.JButton();
        bttListar = new javax.swing.JButton();
        bttDelete = new javax.swing.JButton();
        bttLimpiar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 700));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Control de peliculas");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("ID");

        txtID.setEditable(false);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Titulo");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Director");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Actores");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Origen");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Genero");

        cbGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Estreno");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("En cartelera");

        buttonGroup1.add(rbDisponible);
        rbDisponible.setText("Disponible");

        buttonGroup1.add(rbNodisponible);
        rbNodisponible.setText("Fuera de cartelera");

        jtPeliculas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtPeliculas);

        bttAgg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/guardar.png"))); // NOI18N
        bttAgg.setText("Agregar");
        bttAgg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttAggActionPerformed(evt);
            }
        });

        bttBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-magnifying-glass-tilted-right-48.png"))); // NOI18N
        bttBuscar.setText("Buscar");
        bttBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttBuscarActionPerformed(evt);
            }
        });

        bttUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-aprobar-y-actualizar-48.png"))); // NOI18N
        bttUpdate.setText("Actualizar");
        bttUpdate.setPreferredSize(new java.awt.Dimension(72, 23));
        bttUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttUpdateActionPerformed(evt);
            }
        });

        bttListar.setText("Listar");
        bttListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttListarActionPerformed(evt);
            }
        });

        bttDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/eliminar.png"))); // NOI18N
        bttDelete.setText("Eliminar");
        bttDelete.setPreferredSize(new java.awt.Dimension(72, 23));
        bttDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttDeleteActionPerformed(evt);
            }
        });

        bttLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/escoba.png"))); // NOI18N
        bttLimpiar.setText("Limpiar");
        bttLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtActores)
                                    .addComponent(txtDirector)
                                    .addComponent(txtTitulo)
                                    .addComponent(txtID)
                                    .addComponent(txtorigen)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fechaSeleccionada, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(rbDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbNodisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(cbGenero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bttAgg, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bttBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bttUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bttListar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bttLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bttDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bttAgg, bttBuscar, bttDelete, bttLimpiar, bttListar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtActores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtorigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fechaSeleccionada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(rbDisponible)
                    .addComponent(rbNodisponible))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttAgg, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttListar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bttAgg, bttBuscar, bttDelete, bttLimpiar, bttListar, bttUpdate});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttAggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttAggActionPerformed
        if (txtTitulo.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El titulo es obligatorio");
            return;
        }

        if (txtDirector.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El director es obligatorio");
            return;
        }

        if (txtActores.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Los actores son obligatorios");
            return;
        }

        if (txtorigen.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El origen es obligatorio");
            return;
        }

        if (cbGenero.getSelectedItem() == null || cbGenero.getSelectedItem().toString().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un genero");
            return;
        }

        if (fechaSeleccionada.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una fecha de estreno");
            return;
        }

        if (!rbDisponible.isSelected() && !rbNodisponible.isSelected()) {
            JOptionPane.showMessageDialog(this, "Debe indicar si esta en cartelera o no");
            return;
        }
        List<Pelicula> peliculasExistentes = peliculaData.listarPeliculas();
        for (Pelicula pel : peliculasExistentes) {
            if (pel.getTitulo().equalsIgnoreCase(txtTitulo.getText().trim())) {
                JOptionPane.showMessageDialog(this, "Ya existe una película con ese título.");
                return;
            }
        }

        Pelicula p = new Pelicula();
        p.setTitulo(txtTitulo.getText().trim());
        p.setDirector(txtDirector.getText().trim());
        p.setActores(txtActores.getText().trim());
        p.setOrigen(txtorigen.getText().trim());
        p.setGenero(cbGenero.getSelectedItem().toString());
        p.setEstreno(fechaSeleccionada.getDate());
        p.setEnCartelera(rbDisponible.isSelected());

        peliculaData.guardarPelicula(p);
        JOptionPane.showMessageDialog(this, "Pelicula Agregada Correctamente");
        actualizarTabla();
        limpiarCampos();
    }//GEN-LAST:event_bttAggActionPerformed

    private void configurarTabla() {

        String[] columnas = {"ID", "Titulo", "Director", "Actores", "Origen", "Genero", "Estreno", "En Cartelera"};

        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        jtPeliculas.setModel(modelo);
    }
    private void bttBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttBuscarActionPerformed

        if (txtID.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un ID numérico");
            return;
        }

        int id;
        try {
            id = Integer.parseInt(txtID.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID debe ser un número válido");
            return;
        }

        Pelicula p = peliculaData.buscarPelicula(id);

        if (p != null) {
            txtTitulo.setText(p.getTitulo());
            txtDirector.setText(p.getDirector());
            txtActores.setText(p.getActores());
            txtorigen.setText(p.getOrigen());
            cbGenero.setSelectedItem(p.getGenero());
            fechaSeleccionada.setDate(p.getEstreno());
            rbDisponible.setSelected(p.isEnCartelera());
            rbNodisponible.setSelected(!p.isEnCartelera());

            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jtPeliculas.getModel();
            modelo.setRowCount(0); // Limpia la tabla
            Object[] fila = {
                p.getIdPelicula(),
                p.getTitulo(),
                p.getDirector(),
                p.getActores(),
                p.getOrigen(),
                p.getGenero(),
                p.getEstreno(),
                p.isEnCartelera() ? "Si" : "No"
            };
            modelo.addRow(fila);

            JOptionPane.showMessageDialog(this, "Película encontrada");
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró película con ese ID");
        }


    }//GEN-LAST:event_bttBuscarActionPerformed

    private void cargarDatosDesdeTabla(int fila) {
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jtPeliculas.getModel();

        txtID.setText(modelo.getValueAt(fila, 0).toString());
        txtTitulo.setText(modelo.getValueAt(fila, 1).toString());
        txtDirector.setText(modelo.getValueAt(fila, 2).toString());
        txtActores.setText(modelo.getValueAt(fila, 3).toString());
        txtorigen.setText(modelo.getValueAt(fila, 4).toString());
        cbGenero.setSelectedItem(modelo.getValueAt(fila, 5).toString());
        fechaSeleccionada.setDate((Date) modelo.getValueAt(fila, 6));

        String enCartelera = modelo.getValueAt(fila, 7).toString();
        rbDisponible.setSelected(enCartelera.equals("Si"));
        habilitarModoEdicion();
        reglasHabilitacion();
    }

    private void bttUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttUpdateActionPerformed
        if (txtID.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un ID para actualizar");
            return;
        }

        try {
            Integer.parseInt(txtID.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID debe ser un numero valido");
            return;
        }

        if (txtTitulo.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El titulo es obligatorio");
            return;
        }

        if (txtDirector.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El director es obligatorio");
            return;
        }

        if (txtActores.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Los actores son obligatorios");
            return;
        }

        if (txtorigen.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El origen es obligatorio");
            return;
        }

        if (cbGenero.getSelectedItem() == null || cbGenero.getSelectedItem().toString().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un genero");
            return;
        }

        if (fechaSeleccionada.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una fecha de estreno");
            return;
        }

        if (!rbDisponible.isSelected() && !rbNodisponible.isSelected()) {
            JOptionPane.showMessageDialog(this, "Debe indicar si está en cartelera o no");
            return;
        }

        Pelicula p = new Pelicula();
        p.setIdPelicula(Integer.parseInt(txtID.getText().trim()));
        p.setTitulo(txtTitulo.getText().trim());
        p.setDirector(txtDirector.getText().trim());
        p.setActores(txtActores.getText().trim());
        p.setOrigen(txtorigen.getText().trim());
        p.setGenero(cbGenero.getSelectedItem().toString());
        p.setEstreno(fechaSeleccionada.getDate());
        p.setEnCartelera(rbDisponible.isSelected());

        peliculaData.actualizarPelicula(p);
        JOptionPane.showMessageDialog(this, "Pelicula Actualizada Correctamente");
        actualizarTabla();
        limpiarCampos();
    }//GEN-LAST:event_bttUpdateActionPerformed

    private void actualizarTabla() {
        try {
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jtPeliculas.getModel();
            modelo.setRowCount(0);

            List<Pelicula> peliculas = peliculaData.listarPeliculas();

            for (Pelicula p : peliculas) {
                Object[] fila = {
                    p.getIdPelicula(),
                    p.getTitulo(),
                    p.getDirector(),
                    p.getActores(),
                    p.getOrigen(),
                    p.getGenero(),
                    p.getEstreno(),
                    p.isEnCartelera() ? "Si" : "No"
                };
                modelo.addRow(fila);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al refrescar la tabla: " + e.getMessage());
            e.printStackTrace();
        }
    }

    private void bttListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttListarActionPerformed
        actualizarTabla();
        JOptionPane.showMessageDialog(this, "Lista de peliculas actualizada");
    }//GEN-LAST:event_bttListarActionPerformed

    private void bttDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttDeleteActionPerformed
        if (txtID.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un ID para eliminar");
            return;
        }

        int id;
        try {
            id = Integer.parseInt(txtID.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID debe ser un numero válido");
            return;
        }

        int confirmar = JOptionPane.showConfirmDialog(this, "¿Esta seguro que desea eliminar esta película?", "Confirmar eliminacion", JOptionPane.YES_NO_OPTION);

        try {
            peliculaData.eliminarPelicula(id);
            JOptionPane.showMessageDialog(this, "Película eliminada correctamente");
            actualizarTabla();
            limpiarCampos();
        } catch (Exception ex) {

            // Detecta error por clave foránea (FK)
            if (ex.getMessage().toLowerCase().contains("foreign key")) {
                JOptionPane.showMessageDialog(this,
                    "No se puede eliminar la película porque está asociada a funciones.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,
                    "No se pudo eliminar la película:\n" + ex.getMessage(),
                    "Error SQL",
                    JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_bttDeleteActionPerformed

    private void limpiarCampos() {
        txtID.setText("");
        txtTitulo.setText("");
        txtDirector.setText("");
        txtActores.setText("");
        txtorigen.setText("");
        cbGenero.setSelectedIndex(0);
        fechaSeleccionada.setDate(null);
        rbDisponible.setSelected(false);
        rbNodisponible.setSelected(false);
        jtPeliculas.clearSelection();
        habilitarModoInicial();
    }

    private void bttLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_bttLimpiarActionPerformed

    private void habilitarModoInicial() {

        txtID.setEditable(true);
        txtTitulo.setEditable(true);
        txtDirector.setEditable(true);
        txtActores.setEditable(true);
        txtorigen.setEditable(true);
        cbGenero.setEnabled(true);
        fechaSeleccionada.setEnabled(true);
        rbDisponible.setEnabled(true);
        rbNodisponible.setEnabled(true);

        bttAgg.setEnabled(true);
        bttBuscar.setEnabled(true);
        bttUpdate.setEnabled(false);
        bttDelete.setEnabled(false);
        bttListar.setEnabled(true);
        bttLimpiar.setEnabled(true);
    }

    private void habilitarModoEdicion() {
        txtID.setEditable(false);
        txtTitulo.setEditable(true);
        txtDirector.setEditable(true);
        txtActores.setEditable(true);
        txtorigen.setEditable(true);
        cbGenero.setEnabled(true);
        fechaSeleccionada.setEnabled(true);
        rbDisponible.setEnabled(true);
        rbNodisponible.setEnabled(true);

        bttAgg.setEnabled(false);
        bttBuscar.setEnabled(false);
        bttUpdate.setEnabled(true);
        bttDelete.setEnabled(true);
        bttListar.setEnabled(true);
        bttLimpiar.setEnabled(true);
    }

    private void reglasHabilitacion() {

        boolean haySeleccion = jtPeliculas.getSelectedRow() >= 0;
        boolean idIngresado = !txtID.getText().trim().isEmpty() && !txtID.getText().equals("(Auto)");
        boolean tituloLleno = !txtTitulo.getText().trim().isEmpty();
        boolean directorLleno = !txtDirector.getText().trim().isEmpty();
        boolean actoresLleno = !txtActores.getText().trim().isEmpty();
        boolean origenLleno = !txtorigen.getText().trim().isEmpty();
        boolean generoElegido = cbGenero.getSelectedIndex() >= 0;
        boolean fechaElegida = fechaSeleccionada.getDate() != null;
        boolean carteleraElegida = rbDisponible.isSelected() || rbNodisponible.isSelected();

        boolean datosCompletos = tituloLleno && directorLleno && actoresLleno
                && origenLleno && generoElegido && fechaElegida && carteleraElegida;

        if (!haySeleccion) {
            txtID.setEditable(true);
            txtTitulo.setEditable(true);
            txtDirector.setEditable(true);
            txtActores.setEditable(true);
            txtorigen.setEditable(true);
            cbGenero.setEnabled(true);
            fechaSeleccionada.setEnabled(true);
            rbDisponible.setEnabled(true);
            rbNodisponible.setEnabled(true);

            bttAgg.setEnabled(datosCompletos);
            bttBuscar.setEnabled(idIngresado);
            bttUpdate.setEnabled(false);
            bttDelete.setEnabled(false);
            bttLimpiar.setEnabled(true);
            bttListar.setEnabled(true);
        } else {
            txtID.setEditable(false);
            txtTitulo.setEditable(true);
            txtDirector.setEditable(true);
            txtActores.setEditable(true);
            txtorigen.setEditable(true);
            cbGenero.setEnabled(true);
            fechaSeleccionada.setEnabled(true);
            rbDisponible.setEnabled(true);
            rbNodisponible.setEnabled(true);

            bttAgg.setEnabled(false);
            bttBuscar.setEnabled(false);
            bttUpdate.setEnabled(datosCompletos);
            bttDelete.setEnabled(true);
            bttLimpiar.setEnabled(true);
            bttListar.setEnabled(true);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttAgg;
    private javax.swing.JButton bttBuscar;
    private javax.swing.JButton bttDelete;
    private javax.swing.JButton bttLimpiar;
    private javax.swing.JButton bttListar;
    private javax.swing.JButton bttUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbGenero;
    private com.toedter.calendar.JDateChooser fechaSeleccionada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtPeliculas;
    private javax.swing.JRadioButton rbDisponible;
    private javax.swing.JRadioButton rbNodisponible;
    private javax.swing.JTextField txtActores;
    private javax.swing.JTextField txtDirector;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtorigen;
    // End of variables declaration//GEN-END:variables
}
